# Generated by Django 5.0.7 on 2025-09-13 11:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.CharField(db_index=True, max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DOMAIN", "Domain"),
                            ("IPV4", "IPv4 Address"),
                            ("MD5", "MD5 Hash"),
                            ("SHA1", "SHA1 Hash"),
                            ("SHA256", "SHA256 Hash"),
                        ],
                        max_length=10,
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ThreatReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        help_text="e.g., 'passive_dns', 'whois', 'related_samples'",
                        max_length=50,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        help_text="The raw JSON 'results' from the ThreatMiner API."
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="threat_intel.indicator",
                    ),
                ),
            ],
            options={
                "unique_together": {("indicator", "report_type")},
            },
        ),
    ]
