# Generated by Django 5.0.7 on 2025-09-14 04:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the entity.", max_length=255
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("organization", "Organization"),
                            ("asset", "Asset"),
                        ],
                        help_text="The type of the entity.",
                        max_length=20,
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Flexible key-value pair attributes for the entity.",
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Visual graph coordinates, e.g., {'x': 100, 'y': 200}.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Entity",
                "verbose_name_plural": "Entities",
                "ordering": ["-created_at"],
            },
        ),
    ]
