# Generated by Django 5.0.7 on 2025-09-14 04:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the event.", max_length=255
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        help_text="The date and time the event occurred."
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="A detailed description of the event."
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        help_text="The severity level of the event (e.g., low, medium, high).",
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="The type of event (e.g., communication, transaction).",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Entities involved in this event.",
                        related_name="events",
                        to="core.entity",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        help_text="The location where the event occurred.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["-timestamp"],
            },
        ),
    ]
