# Generated by Django 5.0.7 on 2025-09-13 11:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="URLCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url_to_check", models.URLField(max_length=2048)),
                ("is_phishing", models.BooleanField(default=False)),
                ("in_phishtank_database", models.BooleanField(default=False)),
                (
                    "phishtank_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="The PhishTank ID for the phish.",
                        null=True,
                    ),
                ),
                (
                    "details_url",
                    models.URLField(
                        blank=True,
                        help_text="The PhishTank detail page for the phish.",
                        max_length=2048,
                        null=True,
                    ),
                ),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        help_text="The full JSON response from the PhishTank API.",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
