# Generated by Django 5.0.7 on 2025-09-13 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SerpApiSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        help_text="The SerpAPI engine used, e.g., 'google_news', 'google_scholar'.",
                        max_length=100,
                    ),
                ),
                (
                    "search_parameters",
                    models.JSONField(help_text="The parameters sent to the SerpAPI."),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        help_text="The full JSON response from the SerpAPI."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
