# Generated by Django 5.0.7 on 2025-09-13 10:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiGatewayProxy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_site",
                    models.URLField(
                        help_text="The base URL this proxy is configured for.",
                        max_length=255,
                    ),
                ),
                (
                    "aws_region",
                    models.CharField(
                        help_text="The AWS region where the gateway is deployed.",
                        max_length=50,
                    ),
                ),
                (
                    "api_id",
                    models.CharField(
                        help_text="The AWS API Gateway ID.", max_length=50, unique=True
                    ),
                ),
                (
                    "endpoint_url",
                    models.URLField(
                        help_text="The invocation URL of the API Gateway.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("CREATING", "Creating"),
                            ("DELETING", "Deleting"),
                            ("ERROR", "Error"),
                        ],
                        default="INACTIVE",
                        max_length=10,
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last time this proxy was used.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "API Gateway Proxy",
                "verbose_name_plural": "API Gateway Proxies",
                "ordering": ["-created_at"],
            },
        ),
    ]
