name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  # --- Sourcery auto-fix job (runs only on PRs) ---
  sourcery_autofix:
    name: Sourcery (auto-fix and push)
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Sourcery and tools
        run: |
          python -m pip install --upgrade pip
          pip install "sourcery==1.21.0" "ruff==0.6.8"

      - name: Run Sourcery auto-fix
        run: sourcery review --fix .

      - name: Format after fixes (Ruff)
        run: ruff format .

      # Only push on same-repo PRs (not forks)
      - name: Commit & push if there are changes (same-repo PRs only)
        if: ${{ github.repository == github.event.pull_request.head.repo.full_name }}
        run: |
          set -e
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(sourcery): auto-fix refactors via CI"
            git push
          else
            echo "No Sourcery changes to commit."
          fi

      # Fail if remaining issues require manual fixes
      - name: Final check – fail if issues remain
        run: sourcery review .

  # --- Backend job ---
  backend:
