name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  # --- Sourcery auto-fix job ---
  sourcery_autofix:
    name: Sourcery (auto-fix and push)
    runs-on: ubuntu-latest

    # Run this job only for PR events (avoids undefined pull_request on push)
    if: ${{ github.event_name == 'pull_request' }}

    # Allow the workflow to push to branches in this repository
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Sourcery and tools
        run: |
          python -m pip install --upgrade pip
          pip install "sourcery==1.21.0" "ruff==0.6.8"

      - name: Run Sourcery auto-fix
        run: sourcery review --fix .

      - name: Format after fixes (Ruff)
        run: ruff format .

      # Only commit/push when the PR branch lives in the same repository (not a fork)
      - name: Commit & push if there are changes (same-repo PRs only)
        if: ${{ github.repository == github.event.pull_request.head.repo.full_name }}
        run: |
          set -e
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(sourcery): auto-fix refactors via CI"
            git push
          else
            echo "No Sourcery changes to commit."
          fi

      # Always run a final review; this fails the job if non-auto-fixable issues remain
      - name: Final check – fail if issues remain
        run: sourcery review .

  # --- Backend job ---
  backend:
    runs-on: ubuntu-latest
    needs: [sourcery_autofix]   # lint/test after Sourcery auto-fixes
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies (requirements if present, else pinned toolchain)
        run: |
          python -m pip install --upgrade pip wheel setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt || true; fi
          python -m pip install "ruff==0.6.8" "flake8==7.1.1" "bandit==1.7.9" \
                                "pytest==8.3.2" "pytest-django==4.8.0" "coverage==7.6.1"

      - name: Print versions
        run: |
          python --version
          ruff --version
          flake8 --version
          bandit --version
          pytest --version

      - name: Ruff (lint)
        run: ruff check --output-format=github .

      - name: Ruff (format check)
        run: ruff format --check .

      - name: Flake8
        run: flake8 .

      - name: Bandit
        run: |
          if [ -f ".bandit.yaml" ]; then
            bandit -q -c .bandit.yaml -r .
          elif [ -f ".bandit.yml" ]; then
            bandit -q -c .bandit.yml -r .
          elif [ -f ".bandit" ]; then
            first_char=$(grep -v '^\s*$' .bandit | grep -v '^\s*#' | head -n1 | cut -c1-1 || true)
            if [ "$first_char" = "[" ]; then
              bandit -q -r . -x tests,*/migrations,venv,.venv,node_modules,dist,build -s B101,B311
            else
              bandit -q -c .bandit -r .
            fi
          else
            bandit -q -r . -x tests,*/migrations,venv,.venv,node_modules,dist,build -s B101,B311
          fi

      - name: Pytest
        env:
          DJANGO_SETTINGS_MODULE: config.settings_test
          DJANGO_ENV: test
          NO_EXTERNAL_HTTP: "1"
        run: |
          set +e
          coverage run -m pytest -q
          code=$?
          if [ "$code" = "5" ]; then
            echo "No tests collected (exit 5). Treating as success during bootstrap."
            exit 0
          fi
          exit $code

      - name: Coverage XML
        if: always()
        run: |
          if [ -f ".coverage" ]; then coverage xml -o coverage.xml || true; fi

  # --- Optional web job (lockfile-aware, subfolder-friendly) ---
  web:
    if: ${{ hashFiles('**/package.json') != '' }}
    runs-on: ubuntu-latest
    needs: [sourcery_autofix]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (cached)
        if: ${{ hashFiles('**/package-lock.json') != '' || hashFiles('**/yarn.lock') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setup Node (no cache)
        if: ${{ hashFiles('**/package-lock.json') == '' && hashFiles('**/yarn.lock') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Detect web directory
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          PKG=$(git ls-files **/package.json | head -n1 || true)
          if [ -z "$PKG" ]; then
            echo "skip=1" >> "$GITHUB_OUTPUT"
            echo "No web package.json found; skipping web job."
            exit 0
          fi
          DIR=$(dirname "$PKG")
          echo "dir=$DIR" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        if: ${{ steps.detect.outputs.skip != '1' }}
        shell: bash
        run: |
          set -euo pipefail
          cd "${{ steps.detect.outputs.dir }}"
          if [ -f yarn.lock ]; then
            yarn install --frozen-lockfile
          else
            if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
              npm ci
            else
              npm install
            fi
          fi

      - name: Run tests (fallback to type-check if missing)
        if: ${{ steps.detect.outputs.skip != '1' }}
        shell: bash
        run: |
          set -euo pipefail
          cd "${{ steps.detect.outputs.dir }}"
          if npm run -s test >/dev/null 2>&1; then
            npm test --silent
          elif npm run -s type-check >/dev/null 2>&1; then
            npm run -s type-check
          else
            echo "No test or type-check script found; skipping."
          fi
